# Generated by Django 5.1.2 on 2024-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghotel',
            name='Hotel_cost',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
