# Generated by Django 5.1.1 on 2024-10-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
    ]
