# Generated by Django 5.1.1 on 2024-10-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AddField(
            model_name='record',
            name='customer_ID',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookingHotel',
            fields=[
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('booking_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Arrival_date', models.DateField(max_length=10)),
                ('Departure_date', models.DateField(max_length=10)),
                ('Hotel_Room', models.DateField(max_length=5)),
                ('Hotel_adult', models.BooleanField()),
                ('Hotel_cost', models.IntegerField(max_length=10)),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
            ],
        ),
        migrations.CreateModel(
            name='BookingZoo',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('admission_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('valid_date', models.DateField(max_length=10)),
                ('zoo_adult', models.BooleanField()),
                ('zoo_cost', models.IntegerField(max_length=10)),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
            ],
        ),
    ]
