# Generated by Django 5.1.1 on 2024-10-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_record_id_record_customer_id_bookinghotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghotel',
            name='Hotel_Room',
            field=models.CharField(max_length=5),
        ),
    ]
